sudo: required

language: python

python:
  - "3.6"

services:
  - docker

env:
  - DOCKER_VERSION=17.03
  - DOCKER_VERSION=17.04
  - DOCKER_VERSION=17.05
  - DOCKER_VERSION=17.06

install:
  - docker run -d --privileged --net host --name ci-docker docker:$DOCKER_VERSION-dind dockerd -H tcp://localhost:27015
  - pip install tox codecov

script:
  - DOCKER_HOST=tcp://localhost:27015 tox

after_success:
  - codecov
